[project]
name = "ai-practical-work-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Vyrl-Comms-Tech", email = "vyrlcommstech@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "chainlit>=2.11.1",
    "openai-agents>=0.22.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
ai-practical-work-code = "ai_practical_work_code:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
